version: '2'

services:
    web:
        image: lavoweb/php-8.0
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db:db
    db:
        image: mysql:8.0.23
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "90:80"
        links:
            - db:db
